### ISSUE TITLE
when I turn my switch on and leave the view controller and go back into it, if the switch is enabled it shows the disabled color

### ISSUE THREAD

**Issue by recoveryawareness** [jwd-ali/Switch-Animations#7]
when I turn my switch on and leave the view controller and go back into it, if the switch is enabled it shows the disabled color and it's the same for the oopiste could I pay you to fix this please?

IF YOU WOULD LIKE ME  TO EXPLAIN OR SHOW U A VIDEO OF WHAT I MEAN I CAN DO SO, I WILL HAPPILY PAY U YOU TO FIX THE ISSUE IF THAT WOULD BE OK??

**Comment by jwd-ali** [comment]
Which switch you are trying to use ? its best if you can share video with me 
if its issue with my pod ... I am glad that you mention it and helped me to resolve it. 
I don't need money to fix my library issues 
thank you

**Comment by recoveryawareness** [comment]
YapAnimatedSwitch:

And here is my test project with your custom switch implemented, it's very simple and basic, let me know If it's me who is doing something wrong? https://github.com/recoveryawareness/UITableViewNoStoryboard/blob/main/UITableViewNoStoryboard/Source/ViewControllers/CustomSwitchesGalleryViewController.swift

**Comment by recoveryawareness** [comment]
thank you so much for fixing this issue, should I close the issue now?

**Comment by jwd-ali** [comment]
yeah you can close it now. Thank you
